[package]
name = "dioxus-nui-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
css-minify = "0.3.1"
 
[lib]
proc-macro = true